#!/usr/bin/env python3
"""
DX-7 — DLM founder review sheet as HTML  (catalog build B4 · DX-7)

Standalone HTML renderer for the Decision Language Machine founder review sheet.
It reads the SAME sheet dict produced by
  decision_language_machine_v1/dlm_founder_sheet_v1.py :: build_founder_sheet
and renders the SAME sections/counts as that module's render_founder_sheet_md,
but as one self-contained, theme-aware, brand-neutral HTML page (to a local out/).

This module does NOT edit the DLM module. It imports render_founder_sheet_md only
to prove section/count parity in the test. The sheet dict is generated by running
the DLM pipeline ONCE with all writes redirected to a temp dir (TH-2 pattern), so
nothing lands in the tracked decision_language_machine_v1/output|receipts.

B4 deliverable guards baked in:
  * Lock 10 — the generated HTML carries a visible "DO NOT PUSH" banner and is
    written only to a local out/ path (never a public-hosting path).
  * Every computed metric is watermarked "SYNTHETIC — not a guaranteed claim".
  * UNPOPULATED / empty fields render an explicit badge, never a bare 0/blank that
    reads all-clear (empty-sink vs clean is distinguished).
  * No autonomy or guaranteed-outcome claims; recommended picks render as "hints only".

Dogfood: run_language_gate() runs the repo language_gate (scan/decide, surface="public")
over the rendered HTML. The clean page does NOT FAIL; an injected overclaim
("100% guaranteed") is what makes the gate FAIL — the red-capable proof.

    python3 dx7_founder_sheet_html.py                 # generate sheet -> render out/ -> gate it
    python3 dx7_founder_sheet_html.py --no-gate       # render only
"""
from __future__ import annotations

import argparse
import html
import importlib.util
import json
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "out"                                    # Lock 10: local out/, never a hosting path
OUT_HTML = OUT_DIR / "dlm_founder_sheet.html"

BANNER_TEXT = "DO NOT PUSH — not for public hosting (DLM founder sheet, synthetic pipeline data)"
SYNTHETIC_WATERMARK = "SYNTHETIC — not a guaranteed claim"
HINTS_NOTE = "Recommended picks are hints only — not authority."
FOOTER_NOTE = (
    "This sheet reduces a messy decision backlog to the few items that need a founder. "
    "Counts are produced by the Decision Language Machine's rule-based classifier over the "
    "input backlog; they describe that input only and make no autonomy or outcome promise."
)


# ------------------------------------------------------------------ repo wiring
def _repo_root() -> Path:
    # sg-sandbox root: catalog/builds/DX-7 -> up 3.
    return HERE.parents[2]


def _ensure_paths() -> None:
    for p in (str(_repo_root() / "decision_language_machine_v1"), str(_repo_root() / "language_gate")):
        if p not in sys.path:
            sys.path.insert(0, p)


def _load_gate():
    """Import scan/decide/load_dictionary from the repo language_gate core (no receipt written)."""
    core = _repo_root() / "language_gate" / "language_gate_core_v1.py"
    if "language_gate_core_v1" in sys.modules:
        return sys.modules["language_gate_core_v1"]
    spec = importlib.util.spec_from_file_location("language_gate_core_v1", core)
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(core.parent))
    sys.modules[spec.name] = mod              # register before exec so @dataclass can introspect
    spec.loader.exec_module(mod)
    return mod


def run_language_gate(text: str, surface: str = "public") -> dict:
    """Advisory dogfood: scan text on the given surface and decide. Returns decision + blockers.

    Uses scan/decide directly (not the pipeline) so NO receipt is written into the tracked
    language_gate/receipts dir. Verdict vocab is advisory: CHECK_OK when the gate does not FAIL,
    CHECK_REJECTED when it FAILs.
    """
    gate = _load_gate()
    dictionary = gate.load_dictionary()
    findings, _ = gate.scan(text, surface, dictionary, file_path=None)
    decision, blockers = gate.decide(findings)
    return {
        "origin": "sandbox-advisory",
        "authority": "none",
        "gate_decision": decision,
        "verdict": "CHECK_REJECTED" if decision == "FAIL" else "CHECK_OK",
        "blockers": [
            {"type": b.type, "term": b.term, "line": b.line, "reason": getattr(b, "reason", None)}
            for b in blockers
        ],
    }


# ---------------------------------------------------------- sheet generation
def generate_sheet(input_fixture: Path | None = None) -> dict:
    """Run the DLM pipeline ONCE with all writes redirected to a temp dir; return the sheet dict.

    TH-2 pattern: OUTPUT_DIR / RECEIPTS_DIR on the core module and pipeline are monkeypatched
    to a temp dir so nothing is written into the tracked decision_language_machine_v1 tree.
    """
    _ensure_paths()
    import dlm_core_v1 as core            # noqa: E402
    import dlm_pipeline_v1 as pipe        # noqa: E402

    if input_fixture is None:
        input_fixture = (
            _repo_root() / "decision_language_machine_v1" / "test_fixtures" / "form_official_80_open_v1.json"
        )
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "output"
        rec = Path(tmp) / "receipts"
        core.OUTPUT_DIR = out             # write_run_manifest uses core.OUTPUT_DIR
        core.RECEIPTS_DIR = rec           # write_stage_receipt uses core.RECEIPTS_DIR
        pipe.OUTPUT_DIR = out             # run_pipeline writes sheet/apply_map/processed directly
        summary = pipe.run_pipeline(input_fixture)
        sheet = json.loads(Path(summary["founder_sheet"]).read_text(encoding="utf-8"))
    return sheet


# ---------------------------------------------------------------- rendering
def _e(s) -> str:
    return html.escape(str(s), quote=True)


def _badge_unpopulated(label: str) -> str:
    return f'<span class="badge unpop" title="empty-sink — not the same as clean">UNPOPULATED · {_e(label)}</span>'


def _cluster_block(i: int, c: dict) -> str:
    opts = c.get("options") or []
    if opts:
        opts_html = (
            '<div class="opts"><b>Options:</b><ul>'
            + "".join(f"<li>{_e(o)}</li>" for o in opts)
            + "</ul></div>"
        )
    else:
        opts_html = f'<div class="opts"><b>Options:</b> {_badge_unpopulated("no options on lead item")}</div>'

    members = c.get("member_ids") or []
    if members:
        members_html = f'<div class="members"><b>Member IDs:</b> {_e(", ".join(members))}</div>'
    else:
        members_html = f'<div class="members"><b>Member IDs:</b> {_badge_unpopulated("no members")}</div>'

    return f"""  <section class="cluster">
    <div class="cl-head">
      <span class="cl-idx">{i}</span>
      <h2>[{_e(c.get('cluster_id', ''))}] {_e(c.get('name', ''))}</h2>
    </div>
    <p class="plain">{_e(c.get('plain_english', ''))}</p>
    <div class="ctrl"><b>Controls:</b> {_e(c.get('controls', ''))}</div>
    <div class="ifun"><b>If unanswered:</b> {_e(c.get('if_unanswered', ''))}</div>
    {opts_html}
    {members_html}
  </section>
"""


def _facts_block(facts: list[dict]) -> str:
    if not facts:
        return (
            '  <section class="facts">\n'
            "    <h2>Founder-only facts</h2>\n"
            f"    <p>{_badge_unpopulated('no founder-only facts in this backlog')}</p>\n"
            "  </section>\n"
        )
    rows = "".join(
        f'<li><span class="fid">[{_e(f.get("id",""))}]</span> {_e(f.get("plain_english",""))}</li>'
        for f in facts
    )
    return (
        '  <section class="facts">\n'
        "    <h2>Founder-only facts</h2>\n"
        f"    <ul>{rows}</ul>\n"
        "  </section>\n"
    )


def _machine_queue_block(ids: list[str]) -> str:
    if not ids:
        body = _badge_unpopulated("machine queue empty")
    else:
        preview = ", ".join(ids[:20]) + (" …" if len(ids) > 20 else "")
        body = f'<code class="mq">{_e(preview)}</code>'
    return (
        '  <section class="machine">\n'
        "    <h2>Machine queue (do not ask founder)</h2>\n"
        f"    <p>{body}</p>\n"
        "  </section>\n"
    )


def render_founder_sheet_html(sheet: dict) -> str:
    """Render the founder review sheet dict as one self-contained HTML page.

    Reads the SAME dict shape as decision_language_machine_v1/dlm_founder_sheet_v1.py and
    renders the same sections/counts as render_founder_sheet_md.
    """
    s = sheet["summary"]
    clusters = sheet.get("advisor_clusters", [])
    facts = sheet.get("founder_facts", [])
    mq = sheet.get("machine_queue_ids", [])

    # counts row — each is a SYNTHETIC computed metric
    metric = lambda label, val: (
        f'<div class="metric"><span class="mval">{_e(val)}</span>'
        f'<span class="mlabel">{_e(label)}</span></div>'
    )
    counts_html = "".join([
        metric("Total items", s["total_items"]),
        metric("Advisor clusters", s["advisor_clusters"]),
        metric("Founder facts", s["founder_fact_items"]),
        metric("Machine-validatable", s["machine_validatable"]),
        metric("Deferred", s["deferred"]),
    ])

    clusters_html = "".join(_cluster_block(i, c) for i, c in enumerate(clusters, 1))
    if not clusters:
        clusters_html = (
            '  <section class="cluster">\n'
            f"    <p>{_badge_unpopulated('no advisor clusters — nothing needs a founder')}</p>\n"
            "  </section>\n"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DLM founder review sheet (reduced)</title>
<style>
  :root {{
    --bg:#ffffff; --fg:#1a1d21; --muted:#5b636c; --card:#f6f7f9; --line:#e2e6ea;
    --accent:#3a5bd9; --warn-bg:#fff4d6; --warn-fg:#7a5a00; --warn-line:#e6c65a;
    --unpop-bg:#fde8e8; --unpop-fg:#8a1f1f; --unpop-line:#e0a3a3;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg:#14171a; --fg:#e8ebee; --muted:#9aa3ac; --card:#1d2126; --line:#2c323a;
      --accent:#7d94f4; --warn-bg:#3a3010; --warn-fg:#f3d98a; --warn-line:#6a5a20;
      --unpop-bg:#3a1616; --unpop-fg:#f2a8a8; --unpop-line:#6a2a2a;
    }}
  }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--fg);
    font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }}
  .wrap {{ max-width:880px; margin:0 auto; padding:24px 20px 64px; }}
  .banner {{ background:var(--warn-bg); color:var(--warn-fg); border:1px solid var(--warn-line);
    border-radius:8px; padding:10px 14px; font-weight:600; font-size:13px; margin-bottom:18px; }}
  h1 {{ font-size:24px; margin:6px 0 2px; }}
  .sub {{ color:var(--muted); font-size:13px; margin-bottom:16px; }}
  .synth {{ display:inline-block; background:var(--warn-bg); color:var(--warn-fg);
    border:1px solid var(--warn-line); border-radius:6px; padding:2px 8px; font-size:11px;
    font-weight:700; letter-spacing:.02em; text-transform:uppercase; }}
  .hints {{ border-left:3px solid var(--accent); background:var(--card); padding:8px 14px;
    border-radius:0 6px 6px 0; color:var(--muted); font-size:13px; margin:14px 0 22px; }}
  .metrics {{ display:flex; flex-wrap:wrap; gap:10px; margin:14px 0; }}
  .metric {{ flex:1 1 130px; background:var(--card); border:1px solid var(--line);
    border-radius:10px; padding:12px 14px; }}
  .mval {{ display:block; font-size:26px; font-weight:700; line-height:1; }}
  .mlabel {{ display:block; color:var(--muted); font-size:12px; margin-top:4px; }}
  section {{ margin:16px 0; }}
  .cluster {{ background:var(--card); border:1px solid var(--line); border-radius:10px; padding:14px 16px; }}
  .cl-head {{ display:flex; align-items:baseline; gap:10px; }}
  .cl-idx {{ background:var(--accent); color:#fff; border-radius:50%; width:24px; height:24px;
    display:inline-flex; align-items:center; justify-content:center; font-size:13px; font-weight:700; flex:0 0 auto; }}
  h2 {{ font-size:17px; margin:0; }}
  .plain {{ margin:8px 0; }}
  .ctrl, .ifun, .members {{ font-size:13px; color:var(--muted); margin:4px 0; }}
  .opts {{ font-size:13px; margin:8px 0; }}
  .opts ul, .facts ul {{ margin:6px 0; padding-left:20px; }}
  .badge {{ display:inline-block; border-radius:6px; padding:2px 8px; font-size:11px; font-weight:700; }}
  .badge.unpop {{ background:var(--unpop-bg); color:var(--unpop-fg); border:1px solid var(--unpop-line); }}
  .fid {{ color:var(--accent); font-weight:600; }}
  code.mq {{ display:block; background:var(--card); border:1px solid var(--line); border-radius:8px;
    padding:10px 12px; font-size:12px; word-break:break-word; }}
  footer {{ margin-top:32px; padding-top:14px; border-top:1px solid var(--line);
    color:var(--muted); font-size:12px; }}
</style>
</head>
<body>
<div class="wrap">
  <div class="banner">{_e(BANNER_TEXT)}</div>
  <h1>Founder review sheet (reduced)</h1>
  <div class="sub">Decision Language Machine · {_e(sheet.get('schema', ''))}</div>
  <div><span class="synth">{_e(SYNTHETIC_WATERMARK)}</span></div>

  <div class="metrics">
{counts_html}
  </div>

  <div class="hints">{_e(HINTS_NOTE)}</div>

{clusters_html}
{_facts_block(facts)}
{_machine_queue_block(mq)}

  <footer>{_e(FOOTER_NOTE)}</footer>
</div>
</body>
</html>
"""


def build(out_path: Path = OUT_HTML, sheet: dict | None = None) -> Path:
    if sheet is None:
        sheet = generate_sheet()
    html_out = render_founder_sheet_html(sheet)
    out_path.parent.mkdir(parents=True, exist_ok=True)   # Lock 10: local out/ only
    out_path.write_text(html_out, encoding="utf-8")
    return out_path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT_HTML)
    ap.add_argument("--no-gate", action="store_true", help="render only; skip the language-gate dogfood")
    args = ap.parse_args(argv)

    out = build(args.out)
    print(f"DX-7 rendered -> {out}")

    if args.no_gate:
        return 0

    result = run_language_gate(out.read_text(encoding="utf-8"), surface="public")
    print(f"DX-7 language_gate dogfood: gate_decision={result['gate_decision']}  verdict={result['verdict']}")
    for b in result["blockers"]:
        print(f"  [BLOCK] {b['type']}: {b['term']!r} (line {b['line']})")
    return 0 if result["verdict"] == "CHECK_OK" else 1


if __name__ == "__main__":
    sys.exit(main())
